library(dplyr)
library(ape) 
library(corHMM)
library(phangorn)
library(stringr)
library(here)
library(rotl)
library(ggtree)
library(gsheet)
library(phytools)
library(geiger)
library(ggplot2)
library(rphylopic)
library(RColorBrewer)
library(ggimage)
library(rfishbase)
library(rentrez)
library(taxize)

SV_data <- read.csv("/Users/juliamaja/Desktop/SV/SV_data_avg.csv")
sp_order <- read.csv("/Users/juliamaja/Desktop/SV/Species_order.csv")
source("/Users/juliamaja/Desktop/SV/SV_functions.R")
fishbase_species <- rfishbase::load_taxa()

sp_order_compare <- sp_order %>% left_join(fishbase_species, by = "Species") %>% select("Species", "order", "Order") %>% filter(order != Order)

sp_no_order <- SV_data %>% filter(is.na(Order)) %>% select("Species", "Order")

sp_no_order <- sp_no_order %>% mutate(order_ncbi = ifelse(is.na(Order), purrr::map_chr(Species, get_order_ncbi), order))
